version: '3.2'
services:

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    restart: 'always'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - 'rabbit_python'

  db:
    image: 'mysql'
    restart: 'always'
    env_file:
      - '.env'
    ports:
      - '3306:3306'
    volumes:
      - 'db-volume:/var/lib/mysql'
    networks:
      - 'rabbit_python'

  spider:
    build: './apps/spider/'
    env_file:
      - '.env'
    volumes:
      - type: 'bind'
        source: './processed_files'
        target: '/spider/processed_files'
      - type: 'bind'
        source: './raw_files'
        target: '/spider/raw_files'
      - type: 'bind'
        source: './utils'
        target: '/spider/utils'
    networks:
      - 'rabbit_python'

  sender:
    build: './apps/sender/'
    env_file:
      - '.env'
    volumes:
      - type: 'bind'
        source: './processed_files'
        target: '/sender/processed_files'
      - type: 'bind'
        source: './raw_files'
        target: '/sender/raw_files'
      - type: 'bind'
        source: './utils'
        target: '/sender/utils'
    networks:
      - 'rabbit_python'

networks:
  rabbit_python:
    driver: 'bridge'

volumes:
  db-volume:


